### PR TITLE
added chatbot

### LINKED ISSUE #90: [FEATURE] Integrate a Chatbot for Instant User Support
**Is your feature request related to a problem? Please describe.**
Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

**Describe the solution you'd like**
Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

**Describe alternatives you've considered**

**Additional context**
please assign this to me under gssoc-ext and hacktoberfest

### PR DESCRIPTION
**Pull request by sezallagwal**
closes #90 

https://github.com/user-attachments/assets/059d7be7-1b64-4b9d-baf8-0dd9433c1989

please review this pr thanks! @BamaCharanChhandogi

### CODE REVIEW

**Comment by sezallagwal** [comment]
@BamaCharanChhandogi Can you please review and merge it

**Comment by tmsagarofficial** [comment]
Hi @sezallagwal, Thanks for the effort in trying to integrate a chat bot into the site.

I had some queries regarding the same, Since this bot was created using your account, Further settings and control would move out of the scope of the Project Admin.

I would advice to work alongside @BamaCharanChhandogi to create this chatbot with its own `chatbotId` from an account which @BamaCharanChhandogi has access to.

Thanks again.

**Comment by sezallagwal** [comment]
@tmsagarofficial okay but can you merge this pr and then revert it back since I worked on this

**Comment by tmsagarofficial** [comment]
> @tmsagarofficial okay but can you merge this pr since I worked on this and you can just change the chatbot id later also, code will remain same. you will just have to change this chatbotId: "rBXZd9N6Ar66rTTYQ2ywP" in the code and you will be good to go

Okay yeah,
it will be helpful if you could share what you trained in this version of the bot of your's which has this id of yours.

**Comment by sezallagwal** [comment]
@tmsagarofficial I actually started by pasting the URL, which helped Chatbase auto-train the bot and then I focused on fine-tuning it, adding specific FAQs and training it to handle edge cases effectively. This way it could manage a range of queries and respond naturally to different scenarios!

**Comment by tmsagarofficial** [comment]
Okay, let's merge this and check the integration. Be ready to fix it if we might have to @sezallagwal 😅

**Comment by tmsagarofficial** [comment]
It's working fine and working as intended across devices.
Thanks for contributing 🚀.

**Comment by BamaCharanChhandogi** [comment]
Hi @tmsagarofficial, 
First, check the code locally. If everything is fine, you can merge the `main` branch.

And where the bot exactly, I can not show any bot. please send me a screenshot or something.

**Comment by tmsagarofficial** [comment]
It's at the bottom right.
Yeah, it worked for me.

**Pull request merged**
