### PR TITLE
Done some enhancements in the document and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
I have done the enhancements and also added some new section in the contributing.md file.

I have done these things in the Contributing.md file :-

1) Created a good overall structure.
2) Added need help with the basics section
3) Added a project structure section
4) Added the first pull request section
5) Added alternate way of contributing through GitHub desktop section
6) Added help and support section
7) Added good coding practices section
8) Added pull request process section
9) Added issue report process section

fixes:[#82 ]
closes:[#82 ]

<br>

image

image

image

image

image

### CODE REVIEW

**Review by BamaCharanChhandogi — COMMENTED** [review]
🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer from GitFinder team will review it as soon as possible. We appreciate your support in making this project better

**Comment by milansamuel609** [comment]
I have done all the enhancements. Please kindly check it once.

**Comment by milansamuel609** [comment]
Please review it once if all the changes are fine please merge them.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM,thanks.

**Comment by milansamuel609** [comment]
> LGTM,thanks.

Thank you so much 😊

**Pull request merged**
